version: '2'
services:
    reeactsample-app:
        image: reeactsample
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://reeactsample-mysql:3306/reeactsample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    reeactsample-mysql:
        extends:
            file: mysql.yml
            service: reeactsample-mysql
